apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ingress
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: note.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-frontend-service
            port:
              number: 80
  - host: api.note.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-backend-service
            port:
              number: 80