replicas: 2

image:
  name: d4rq/note-front
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

env:
  VITE_API_BASE_URL: "http://api.note.ru"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1