apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: back
type: Opaque
data:  
  database-connection: U2VydmVyPTE5Mi4xNjguMC4xMDI6NTQzMjtEYXRhYmFzZT1maWxlZHVtcDtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPWQ0cnFnZzs=
  jwt-secret: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXktaGVyZS1samtzZGJmMDkxMmgwOGRiYXNkYi1samtzZGJmMDkxMmgwOGRiYXNkYi1samtzZGJmMDkxMmgwOGRiYXNkYg==
  minio-access-key: cm9vdHVzZXI=
  minio-secret-key: cm9vdHBhc3N3b3Jk