apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
{{ include "db.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}