apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  clusterIP: None
  ports:
    {{- with .port }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  {{- end }}
  selector:
{{- include "db.selectorLabels" . | nindent 4 }}