apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}-deployment
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  strategy:
    {{- with .Values.strategy }}
        {{- toYaml . | nindent 4 }}
    {{- end }}