apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: back
type: Opaque
data:  
  connection-string: SG9zdD1wb3N0Z3Jlcy1zdmMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPWZpbGVkdW1wO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzbWFzdGVyOwo=
  jwt-secret: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1rZXktaGVyZS1samtzZGJmMDkxMmgwOGRiYXNkYi1samtzZGJmMDkxMmgwOGRiYXNkYi1samtzZGJmMDkxMmgwOGRiYXNkYg==