apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
    {{- with .Values.service }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      type: {{ .type }}
    {{- end }}