apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
{{ include "consumer.labels" . | indent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  {{- with .port }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  {{- end }}
  selector:
{{- include "consumer.selectorLabels" . | nindent 4 }}